development:
  adapter: postgresql
  encoding: unicode
  database: SOTD_deveopment
  pool: 2
  host: localhost
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: SOTD_production
  pool: 2
  username:
password: